# Generated by Django 2.2.12 on 2021-11-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=64, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('Music Production', 'Music Production'), ('Software Development', 'Software Development'), ('Computer Gaming', 'Computer Gaming')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16)),
                ('address', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Bangla', 'Bangla'), ('Hindi', 'Hindi')], max_length=32, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
